language: python
python:
  - "3.6"

dist: trusty
sudo: false

branches:
  only:
    - master

# command to install dependencies
install:
- pip install -U pytest
- pip install -U -r requirements.txt

# command to run the tests
script:
- python -m compileall ./ #Using this to do a Syntax Check
- python -m pytest tests/